### ISSUE TITLE
Load Icons from other sources

### ISSUE THREAD

**Issue by jiangyi0923** [knoxfighter/arcdps-extension#6]
can you support to load local or linked images?

**Comment by knoxfighter** [comment]
The `IconLoader` is able to load linked images (added to a program as resource). The function `void* getTexture(UINT name);` takes a resourceID as parameter. That parameter just can be one of the macros in `resource.h`.
Loading local files (on disk) is not possible, but eventually i will support that in the future :)
You can alwas add it yourself and create a PR with the changes .

**Comment by knoxfighter** [comment]
Support to load icons from File and from an http link added.
